inputs:

{ config, lib, pkgs, ... }:

let
  inherit (lib) mkIf;
  cfg = config.programs.inir;

  inirSource = inputs.inir;

  polkitAgentPath =
    let
      matePolkit = lib.attrByPath [ "mate" "mate-polkit" ] null pkgs;
      matePolkitFlat = lib.attrByPath [ "mate-polkit" ] null pkgs;
      polkitGnome = lib.attrByPath [ "polkit_gnome" ] null pkgs;
    in
      if matePolkit != null then "${matePolkit}/libexec/polkit-mate-authentication-agent-1"
      else if matePolkitFlat != null then "${matePolkitFlat}/libexec/polkit-mate-authentication-agent-1"
      else if polkitGnome != null then "${polkitGnome}/libexec/polkit-gnome-authentication-agent-1"
      else "/usr/lib/mate-polkit/polkit-mate-authentication-agent-1";

  quickshellConfig = pkgs.runCommand "inir-quickshell-config" {
    buildInputs = [ pkgs.bash cfg.internal.pythonEnv ];
  } ''
    mkdir -p $out

    for qml_file in ${inirSource}/*.qml; do
      if [ -f "$qml_file" ]; then
        cp "$qml_file" $out/$(basename "$qml_file")
      fi
    done

    for dir in modules services scripts assets translations sdata; do
      if [ -d "${inirSource}/$dir" ]; then
        cp -r "${inirSource}/$dir" "$out/$dir"
      fi
    done

    chmod -R u+rwX $out

    # Replace hard-coded /usr/bin paths for Nix-friendly ones
    find $out -type f \( -name "*.qml" -o -name "*.sh" -o -name "*.fish" -o -name "*.py" -o -name "*.js" \) -print0 \
      | xargs -0 sed -i \
        -e "s|/usr/bin/df|${pkgs.coreutils}/bin/df|g" \
        -e "s|/usr/bin/pgrep|${pkgs.procps}/bin/pgrep|g" \
        -e "s|/usr/bin/whoami|${pkgs.coreutils}/bin/whoami|g" \
        -e "s|/usr/bin/bash|${pkgs.bash}/bin/bash|g" \
        -e "s|/usr/bin/pidof|${pkgs.procps}/bin/pidof|g" \
        -e "s|/usr/bin/which|${pkgs.which}/bin/which|g" \
        -e "s|/usr/bin/nmcli|${pkgs.networkmanager}/bin/nmcli|g" \
        -e "s|/usr/bin/find|${pkgs.findutils}/bin/find|g" \
        -e "s|/usr/bin/gsettings|${pkgs.glib}/bin/gsettings|g" \
        -e "s|/usr/bin/sh|${pkgs.bash}/bin/sh|g" \
        -e "s|/usr/bin/trans|${pkgs.translate-shell}/bin/trans|g" \
        -e "s|/usr/bin/flatpak|${pkgs.flatpak}/bin/flatpak|g" \
        -e "s|/usr/bin/qs|qs|g"

    # Fix complex python shebangs that reference a venv
    find $out -name "*.py" -print0 | xargs -0 sed -i 's|^#!.*ILLOGICAL_IMPULSE_VIRTUAL_ENV.*|#!/usr/bin/env python3|'

    # Ensure scripts are executable
    if [ -d "$out/scripts" ]; then
      find $out/scripts -type f \( -name "*.sh" -o -name "*.fish" -o -name "*.py" \) -exec chmod +x {} \;
    fi

    patchShebangs $out
  '';

in {
  config = mkIf cfg.enable {
    # Fake venv for scripts to use the Nix python environment
    home.file = {
      ".local/state/quickshell/.venv/bin/activate".text = ''
        # Generated by iNiR flake
        export VIRTUAL_ENV="${cfg.internal.pythonEnv}"
        export PATH="${cfg.internal.pythonEnv}/bin:$PATH"
        deactivate () {
            return 0
        }
      '';
      ".local/state/quickshell/.venv/bin/python".source = "${cfg.internal.pythonEnv}/bin/python";
      ".local/state/quickshell/.venv/bin/python3".source = "${cfg.internal.pythonEnv}/bin/python3";
      ".local/state/quickshell/.venv/pyvenv.cfg".text = ''
        home = ${cfg.internal.pythonEnv}/bin
        include-system-site-packages = false
        version = 3.11.0
      '';
    };

    xdg.configFile = {
      "quickshell/ii".source = quickshellConfig;
      "fuzzel/fuzzel.ini".source = "${inirSource}/defaults/fuzzel/fuzzel.ini";
      "matugen".source = "${inirSource}/defaults/matugen";
      "gtk-3.0/settings.ini".source = "${inirSource}/defaults/gtk-3.0/settings.ini";
      "gtk-4.0/settings.ini".source = "${inirSource}/defaults/gtk-4.0/settings.ini";
      "dolphinrc".source = "${inirSource}/defaults/kde/dolphinrc";
    };

    home.activation.inirDefaults = config.lib.dag.entryAfter [ "writeBoundary" ] ''
      # Create required state directories
      $DRY_RUN_CMD mkdir -p "${config.xdg.stateHome}/quickshell/user/generated/wallpaper"
      $DRY_RUN_CMD mkdir -p "${config.xdg.stateHome}/quickshell/user/generated"
      $DRY_RUN_CMD mkdir -p "${config.xdg.stateHome}/quickshell/user"
      $DRY_RUN_CMD mkdir -p "${config.xdg.stateHome}/quickshell"

      # Install config.json if missing
      if [ ! -f "${config.xdg.configHome}/illogical-impulse/config.json" ]; then
        $DRY_RUN_CMD mkdir -p "${config.xdg.configHome}/illogical-impulse"
        $DRY_RUN_CMD cp "${inirSource}/defaults/config.json" "${config.xdg.configHome}/illogical-impulse/config.json"
        $DRY_RUN_CMD chmod u+w "${config.xdg.configHome}/illogical-impulse/config.json"
      fi

      # Install Niri config if missing
      if [ ! -f "${config.xdg.configHome}/niri/config.kdl" ]; then
        $DRY_RUN_CMD mkdir -p "${config.xdg.configHome}/niri"
        $DRY_RUN_CMD cp "${inirSource}/defaults/niri/config.kdl" "${config.xdg.configHome}/niri/config.kdl"
        $DRY_RUN_CMD chmod u+w "${config.xdg.configHome}/niri/config.kdl"
        $DRY_RUN_CMD sed -i "s|/usr/lib/mate-polkit/polkit-mate-authentication-agent-1|${polkitAgentPath}|g" "${config.xdg.configHome}/niri/config.kdl"
      fi

      # Ensure kdeglobals is writable (scripts modify it)
      if [ -L "${config.xdg.configHome}/kdeglobals" ]; then
        $DRY_RUN_CMD rm "${config.xdg.configHome}/kdeglobals"
      fi

      if [ ! -f "${config.xdg.configHome}/kdeglobals" ]; then
        $DRY_RUN_CMD cp "${inirSource}/defaults/kde/kdeglobals" "${config.xdg.configHome}/kdeglobals"
        $DRY_RUN_CMD chmod u+w "${config.xdg.configHome}/kdeglobals"
      else
        $DRY_RUN_CMD chmod u+w "${config.xdg.configHome}/kdeglobals"
      fi

      # Install dolphin panel layout state if missing
      if [ ! -f "${config.xdg.stateHome}/dolphinstaterc" ]; then
        $DRY_RUN_CMD mkdir -p "${config.xdg.stateHome}"
        $DRY_RUN_CMD cp "${inirSource}/defaults/kde/dolphinstaterc" "${config.xdg.stateHome}/dolphinstaterc"
        $DRY_RUN_CMD chmod u+w "${config.xdg.stateHome}/dolphinstaterc"
      fi
    '';
  };
}
